version: '3.8'

services:
  mini-crm:
    build: .
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./mini_crm.db
    networks:
      - web

networks:
  web:
    external: true
